name: Changelog

on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "üì• Check-out"
        uses: actions/checkout@v1
      - name: "‚úèÔ∏è Generate release changelog"
        id: generate-release-changelog
        uses: heinrichreimer/github-changelog-generator-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: "true"
          stripHeaders: "true"
          stripGeneratorNotice: "true"
          pullRequests: "false"
          unreleased: "false"
      - run: |
          set -e
          git add CHANGELOG.md
          git commit -m 'Updated CHANGELOG.md'
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
